# Generated by Django 4.1.5 on 2023-03-31 15:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_alter_filemodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='storage'), upload_to=''),
        ),
    ]
