# Generated by Django 4.1.5 on 2023-01-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
