# Generated by Django 4.1.5 on 2023-01-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_remove_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='storage/'),
        ),
    ]
