# Generated by Django 4.1.5 on 2023-01-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_filemodel_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='native_file_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='filemodel',
            unique_together={('user_id', 'native_file_name')},
        ),
    ]
