# Generated by Django 4.1.5 on 2023-01-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_alter_filemodel_native_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='comment',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='last_download_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
