# Generated by Django 4.1.5 on 2023-01-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_filemodel_comment_filemodel_last_download_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
